* Examples from manual and guide
** Document structure
*** Headlines
**** Third level headline
*** Visibility
**** Initial visibility
#+STARTUP: overview
#+STARTUP: content
#+STARTUP: showall
#+STARTUP: showeverything
**** Catching invisible edits
Set org-catch-invisible-edits to non-nil

*** Plain lists
My favorite scenes are (in this order)
1. The attack of the Rohirrim
2. Eowyn's fight with the witch king
   + this was already my favorite scene in the book
   + I really like Miranda Otto.
3. Peter Jackson being shot by Legolas
   - on DVD only
   He makes a really funny face when it happens.
But in the end, no individual scenes matter but the film as a whole.
Important actors in this film are:
- Elijah Wood :: He plays Frodo
- Sean Astin :: He plays Sam, Frodo's friend. I still remember him
     very well from his role as Mikey Walsh in /The Goonies/.

*** Drawers
Still outside the drawer
:DRAWERNAME:
This is inside the drawer.
It can be multiple lines
:END:
After the drawer.

*** Blocks
    Blocks are like this:
    #+BEGIN
    This is inside the block
    #+END
    To fold and unfold blocks, press TAB on the BEGIN line

*** Footnotes
    Footnotes can be named[fn:NAME] or numbered, and inline or defined seperately[fn:2]. Numbered footnotes can be
    renumbered and sorted automatically. The footnote action command is C-c C-x f
    *examples*:
    [fn:1: first inline footnote]
    [fn:: anonymus inline footnote]
[fn:NAME] Named footnote defined seperately, there must be no indentation
[fn:2] This footnote is defined seperately

** Tables
   | Name  | Phone | Age |
   |-------+-------+-----|
   | Peter |  1234 |  17 |
   | Anna  |  4321 |  25 |
** Hyperlinks
*** Links
    *format*: [[link] [description]] (without the space)
    *example*: [[link][description]]
    To edit the invisible ‘link’ part, use C-c C-l with the cursor on the link.
    To follow the link, use C-c C-o
    To go back, use C-c &
    To save position, use C-c %
**** Internal links
     :PROPERTIES:
     :CUSTOM_ID: internal-links
     :END:
     If the link does not look like a URL, it is considered to be internal in the current file.
     The most important case is a link like ‘[[#my-custom-id]]’ which will link to the entry with the
     CUSTOM_ID property ‘my-custom-id’.
     *example*: [[#internal-links][Internal links]]
     Links such as ‘[[My Target]]’ or ‘[[My Target][Find my target]]’ lead to a text search in the current file for
     the corresponding target which looks like ‘<<My Target>>’. 
**** External links
     Links can be external, we can link to websites, files, etc, you can find all the examples here:
     [[https://orgmode.org/guide/External-links.html#External-links][External link examples]]
     [[nihongo.org][This is a link to the japanese language notes]]
     If the description is a file name or URL that points to an image, HTML export (see [[https://orgmode.org/guide/HTML-export.html#HTML-export][HTML export]])
     will inline the image as a clickable button. If there is no description at all and the link
     points to an image, that image will be inlined into the exported HTML file.
**** Targeted links
     *examples*:
     - [[file:~/code/main.c::255]]                 Find line 255
     - [[file:~/xx.org::My Target]]                Find ‘<<My Target>>’
     - [[file:~/xx.org::#my-custom-id]]            Find entry with custom id
